url: http://simad.github.io
baseurl:

# Site Settings
title: Silvia's Lair
author: Silvia
author_full: Silvia Mandalà
description: "Personal site"
keywords: "jekyll, coding"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/start.png"

likes: ["Coffee", "Photography", "Scala", "Guitars", "Craftsmanship", "Swift", "Food", "Testing", "Bouldering", "Sarcasm", "Party Parrots"]
exclude: ["Rakefile", "LICENSE", "readme.markdown"]
